# Generated by Django 3.2.7 on 2021-10-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addtrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=30, null=True)),
                ('train_id', models.IntegerField(null=True)),
                ('Seats_availability', models.IntegerField(null=True)),
                ('Compartment_type', models.CharField(choices=[('Firstclass', '1A'), ('AC2tier class', 'AC2tier class'), ('AC 3tier class', 'AC 3tier class'), ('Sleeper class', 'Sleeper class'), ('Second class', 'Second class'), ('General class', 'General class')], max_length=30, null=True)),
                ('Source', models.CharField(max_length=30, null=True)),
                ('Destination', models.CharField(max_length=30, null=True)),
                ('Departure_time', models.CharField(max_length=30, null=True)),
                ('Arrival_time', models.CharField(max_length=30, null=True)),
                ('Travel_time', models.CharField(max_length=50, null=True)),
                ('Fare', models.IntegerField(null=True)),
            ],
        ),
    ]
