# Generated by Django 3.2.7 on 2021-10-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='Destination_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='Source_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='Train_id',
            field=models.IntegerField(null=True),
        ),
    ]
