# Generated by Django 3.2.7 on 2021-10-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211020_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='Destination_id',
        ),
        migrations.RemoveField(
            model_name='train',
            name='Source_id',
        ),
        migrations.AddField(
            model_name='train',
            name='Destination',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='Source',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
