# Generated by Django 3.2.7 on 2021-10-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='Phone_no',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
