# Generated by Django 3.2.7 on 2021-10-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_final_compartment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='final',
            old_name='PNR_no',
            new_name='Aadhar_no',
        ),
    ]
