# Generated by Django 3.2.7 on 2021-10-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_pnr_no_final_aadhar_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route_id', models.IntegerField(null=True)),
                ('Train_id', models.IntegerField(null=True)),
                ('Source', models.CharField(max_length=30, null=True)),
                ('Destination', models.CharField(max_length=30, null=True)),
                ('Arrival_time', models.CharField(max_length=30, null=True)),
                ('Departure_time', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
