# Generated by Django 3.2.7 on 2021-10-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, null=True)),
                ('E_mail', models.CharField(max_length=40, null=True)),
                ('Password', models.IntegerField(null=True)),
                ('Phone_no', models.CharField(max_length=40, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Gender', models.CharField(max_length=30, null=True)),
                ('Aadhar_no', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
