# Generated by Django 3.2.7 on 2021-10-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211028_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_mail', models.CharField(max_length=40, null=True)),
                ('PNR_id', models.IntegerField(null=True)),
                ('Train_id', models.IntegerField(null=True)),
                ('Reserved_mode', models.CharField(max_length=30, null=True)),
                ('Reserved_date', models.DateField(null=True)),
                ('Booked_status', models.CharField(max_length=30, null=True)),
                ('no_of_booked_seats', models.IntegerField(null=True)),
                ('Compartment_id', models.IntegerField(null=True)),
                ('Route_id', models.IntegerField(null=True)),
                ('Booked_amount', models.IntegerField(null=True)),
            ],
        ),
    ]
