# Generated by Django 3.2.7 on 2021-10-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compartment_id', models.IntegerField(null=True)),
                ('Compartment_type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route_id', models.IntegerField(null=True)),
                ('Source_id', models.IntegerField(null=True)),
                ('Destination_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station_id', models.IntegerField(null=True)),
                ('Station_name', models.CharField(max_length=30, null=True)),
                ('Source_id', models.IntegerField(null=True)),
                ('Destination_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_id', models.IntegerField(null=True)),
                ('Train_name', models.CharField(max_length=30, null=True)),
                ('Source_id', models.IntegerField(null=True)),
                ('Destination_id', models.IntegerField(null=True)),
            ],
        ),
    ]
