# Generated by Django 3.2.7 on 2021-10-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_compartment_routedetail_station_traindetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartmentmapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_id', models.IntegerField(null=True)),
                ('Compartment_id', models.IntegerField(null=True)),
                ('Total_no_of_seats', models.IntegerField(null=True)),
                ('Available_no_of_seats', models.IntegerField(null=True)),
                ('Booking_fare', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_id', models.IntegerField(null=True)),
                ('Available_date', models.DateField(null=True)),
                ('Sunday', models.CharField(max_length=30, null=True)),
                ('Monday', models.CharField(max_length=30, null=True)),
                ('Tuesday', models.CharField(max_length=30, null=True)),
                ('Wednesday', models.CharField(max_length=30, null=True)),
                ('Thursday', models.CharField(max_length=30, null=True)),
                ('Friday', models.CharField(max_length=30, null=True)),
                ('Saturday', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routemapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route_id', models.IntegerField(null=True)),
                ('Train_id', models.IntegerField(null=True)),
                ('Arrival_time', models.CharField(max_length=30, null=True)),
                ('Departure_time', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
