# Generated by Django 3.2.7 on 2021-10-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_compartmentmapping_daydetail_routemapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routemapping',
        ),
        migrations.RenameField(
            model_name='traindetail',
            old_name='Destination_id',
            new_name='Route_id',
        ),
        migrations.RemoveField(
            model_name='daydetail',
            name='Available_date',
        ),
        migrations.RemoveField(
            model_name='station',
            name='Destination_id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='Source_id',
        ),
        migrations.RemoveField(
            model_name='traindetail',
            name='Source_id',
        ),
        migrations.AddField(
            model_name='compartmentmapping',
            name='Booked_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='traindetail',
            name='Arrival_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='traindetail',
            name='Departure_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
